print('丁凯峰\n学号: 2302190128')
a, b = input("请输入数字:\n").split()
a = int(a)
b = int(b)
print(f'{a}+{b}={a + b:2}')
print('{0}+{1}={2:2}'.format(a, b, a + b))
print(f'{a}-{b}={a - b:.2f}')
print('{0}-{1}={2}'.format(a, b, a - b))
print(f'{a}*{b}={a * b}')
print('{0}*{1}={2}'.format(a, b, a * b))
print(f'{a}/{b}={a / b:.2f}')
print('{0}/{1}={2:.2f}'.format(a, b, a / b))
