print('丁凯峰\n学号: 2302190128')
year = input('请输入年份:')
month = input('请输入月份:')
data = input('请输入日期:')
print(year, month, data, sep=' ')
print(year, month, data, sep='-')
print(year, month, data, sep='/')
print(month, data, year, sep=',')
print('{0}年{1}月{2}日'.format(year, month, data))
print(year+'年'+month+'月'+data+'日')
